### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by Yuma6128** [Yuma6128/protospace-36167#1]
URL
https://protospace-36167.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるようにしましょう**
「さん」が抜けているため修正しましょう。

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するようにしましょう**
プロトタイプ名をクリックしたときに遷移しません。

- [x] **プロトタイプ詳細ページにて、ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されるようにしましょう**
「投稿者」が表示されていません。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
